version: "3"
services:
    adventureworks:
        build: ./src
        environment:
            SA_PASSWORD: "AdventureWorks1234"
            ACCEPT_EULA: "Y"
            MSSQL_AGENT_ENABLED: "true"
        ports:
            - "1001:1433"
        container_name: adventureworks
        hostname: adventureworks