version: "3"
services:
    adventureworks2019:
        build: ./src
        environment:
            SA_PASSWORD: "AdventureWorks1234"
            ACCEPT_EULA: "Y"
            MSSQL_AGENT_ENABLED: "true"
            MSSQL_COLLATION: "Latin1_General_CI_AS"
            MSSQL_PID: "Developer"
        ports:
            - "2019:1433/tcp"
        container_name: adventureworks2019
        hostname: adventureworks2019
        stdin_open: true
        tty: true